server {
    listen 80;
    server_name localhost;

    # El directorio donde Nginx buscará los archivos estáticos
    root /usr/share/nginx/html;
    # El archivo por defecto (index) de la aplicación
    index index.html;

    # Bloque principal que intercepta todas las rutas
    location / {
        # Intenta cargar la ruta exacta (ej: /assets/imagen.png), 
        # luego el directorio, 
        # y si no existe, redirige siempre al index.html (Vital en Angular/Ionic para que el router de la app tome el control)
        try_files $uri $uri/ /index.html;
    }
}